version: '3.8'

# services:
#   laravel:
#     build: .
#     container_name: laravel-api
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/contact-service/app
#     working_dir: /app
#     version: "3.8"

services:
  backend:
    build:
      context: ./contacts-service
      dockerfile: Dockerfile
    container_name: contacts-api
    volumes:
      - ./contact-service:/var/www/html
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
      